# -*- coding: utf-8 -*-
"""data_eng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K_F3L6lIYL_EVJv2dLQkxlp7QOFlhdXd
"""

import pandas as pd

#reading csv file form url
df=pd.read_csv("http://13.234.66.67/summer19/datasets/info.csv")

df

x=df.iloc[:,0:].values

#removing missing value or replacing missing vLUE WITH relevant data
#df.describe()
from sklearn.preprocessing import Imputer

imp= Imputer(missing_values='NaN',axis=0,strategy='mean')

impute=imp.fit(x[:,1:3])#this is only fitting of column that we want to process

#time for transforming the fitted columns
x[:,1:3]=impute.transform(x[:,1:3])

x

#string label int //float
from sklearn.preprocessing import LabelEncoder

cont=LabelEncoder() #this is for counntry labeling

#now applying colummn 1st in this labelEn
x[:,0]=cont.fit_transform(x[:,0])

x

# labeling last column
p=LabelEncoder()

x[:,3]=p.fit_transform(x[:,3])

x

#now encoding 1st column --making subcolumn first column 
from sklearn.preprocessing import OneHotEncoder

firstcl=OneHotEncoder(categorical_features=[0]) #defining exact column number where we want to maken category

x=firstcl.fit_transform(x).toarray()

x

x.astype(int)

